### ISSUE TITLE
Error in dependencies

### ISSUE THREAD

**Issue by tonidorta** [kuflow/kuflow-sdk-java#48]
After downloading the sample Workflow implementation and running it, I get an error about the dependencies. 

Please see attached file with details.
![error](https://github.com/kuflow/kuflow-sdk-java/assets/10433056/499df1b6-c6db-4c9e-bfe1-0eb17373015e)

**Comment by jrpedrianes** [comment]
Thaks @tonidorta , we detect a dependency conflict in the SDK.

We are fixing it and we'll make a new release ASAP.
